import "@mantine/core/styles.css";
import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans, Poppins } from "next/font/google";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";

const notoSans = Noto_Sans({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });
const poppins = Poppins({ subsets: ["latin"], weight: "800", variable: "--font-poppins" });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${notoSans.className} ${poppins.variable}`}>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
